### ISSUE TITLE
Value is required when updating marketplace

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#1094]
**Version Info**
19.0 with sample data.

**Describe the bug**
When trying to update sample marketplace the error "Value is required" is shown

**How to Reproduce**
1. Install OSCM with sampledata=true
2. Go to update marketplace
3. Update value
3. Klick save button

**Additional context**
10/08/2020_12:23:16.589 FSP_INTS-BSS: WARN: ThreadID https-jsse-nio-8081-exec-8: BLValidator: 40030: Validation failed
org.oscm.internal.types.exception.ValidationException: EXCEPTIONID 1602159796589: Validation failed for member marketplace.name with reason REQUIRED (parameters=[marketplace.name]).
        at org.oscm.validator.BLValidator.isNotBlank(BLValidator.java:115) [oscm-common.jar:?]
        at org.oscm.marketplace.bean.MarketplaceServiceLocalBean.updateMarketplace(MarketplaceServiceLocalBean.java:564) [oscm-marketplaceservice.jar:PRIVATE-BUILD-ON-DE15702524C9-20200921091141]
        at org.oscm.marketplace.bean.MarketplaceServiceLocalBean.updateMarketplace(MarketplaceServiceLocalBean.java:669) [oscm-marketplaceservice.jar:PRIVATE-BUILD-ON-DE15702524C9-20200921091141]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.oscm.interceptor.AuditLogDataInterceptor.logAuditLogData(AuditLogDataInterceptor.java:29) [oscm-server-common.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.oscm.interceptor.ExceptionMapper.mapEJBExceptions(ExceptionMapper.java:49) [oscm-server-common.jar:?]
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.oscm.interceptor.InvocationDateContainer.setTransactionTime(InvocationDateContainer.java:41) [oscm-server-common.jar:?]
        at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:191) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:102) [openejb-core-7.1.1.jar:7.1.1]
        at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:252) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347) [openejb-core-7.1.1.jar:7.1.1]
        at com.sun.proxy.$Proxy378.updateMarketplace(Unknown Source) [?:?]
        at org.oscm.internal.marketplace.MarketplaceServiceManagePartnerBean.updateMarketplace(MarketplaceServiceManagePartnerBean.java:91) [oscm-internal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205) [openejb-core-7.1.1.jar:7.1.1]
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186) [openejb-core-7.1.1.jar:7.1.1]
        at org.oscm.interceptor.ExceptionMapper.mapEJBExceptions(ExceptionMapper.java:49) [oscm-server-common.jar:?]

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-dockerbuild/pull/278
