### ISSUE TITLE
Azure Instance: after execute operation "start", the detail shows state stopped

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#152]
[Build]
docker 17.7 2018/10/05

[Steps to reproduce]
create a azure instance
go to My Subscription
click the subscription
instance is running and 
![start1](https://user-images.githubusercontent.com/15209605/46528163-62e93b00-c893-11e8-8f7b-5a4f87e975e6.PNG)
![start2](https://user-images.githubusercontent.com/15209605/46528164-6381d180-c893-11e8-9eaf-c593083f258b.PNG)

details shows state "running"
select "stop" and click execute
the instance is stopped and details shows state "stopped"
select "start" and click execute

[Expected result]
the instance is running and the details shows: state "running"

[Observed result]
the instance is running and the details shows: state "stopped"

**Comment by elfriedegoetz** [comment]
sorry the attachement are on wrong position, it should be inserted at the end

**Comment by GoebelL** [comment]
@elfriedegoetz 
What is shown in the operations view? Please check the result of the start operation in **Home > Account > Operations**. Is the start operation failed? If yes, is there further log information? Your answers help me to prioritize this issue.

**Comment by elfriedegoetz** [comment]
![operation](https://user-images.githubusercontent.com/15209605/46856503-e7ddd280-ce06-11e8-93bd-a7fc04c1891a.PNG)

**Comment by elfriedegoetz** [comment]
Home > Account > Operations shows: "start" Completed

**Comment by ghost** [comment]
After investigating the issue I have come to the conclusion that It is not directly related to the azure controller, but rather to all operations that can be executed on provisioned machines (in every controller).

The issue is not 100% reproducible and happens very randomly. When it happens, we can see in the logs:
```
22-Oct-2018 11:04:43.215 SEVERE [EjbTimerPool - 3] org.apache.openejb.core.transaction.EjbTransactionUtil.handleSystemException EjbTransactionUtil.handleSystemException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
 javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.wrapStaleStateException(AbstractEntityManagerImpl.java:1729)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1634)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:560)
        at org.oscm.app.dao.OperationDAO.getOperationByInstanceId(OperationDAO.java:55)
        at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:100)
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:252)
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347)
        at org.oscm.app.dao.OperationDAO$$LocalBeanProxy.getOperationByInstanceId(org/oscm/app/dao/OperationDAO.java)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.notifyOnProvisioningCompletion(APPTimerServiceBean.java:931)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleControllerProvisioning(APPTimerServiceBean.java:358)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleSystems(APPTimerServiceBean.java:281)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.handleTimer(APPTimerServiceBean.java:248)
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.AroundTimeout(StatsInterceptor.java:145)
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.singleton.SingletonContainer._invoke(SingletonContainer.java:272)
        at org.apache.openejb.core.singleton.SingletonContainer.invoke(SingletonContainer.java:221)
        at org.apache.openejb.core.timer.EjbTimerServiceImpl.ejbTimeout(EjbTimerServiceImpl.java:800)
        at org.apache.openejb.core.timer.EjbTimeoutJob.execute(EjbTimeoutJob.java:39)
        at org.apache.openejb.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
        at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
        at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
        at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3071)
        at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2950)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3330)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:560)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:434)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:50)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1251)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1319)
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
        at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:529)
        ... 46 more
```

Related code:
https://github.com/servicecatalog/oscm/blob/dbd251fe61def705bb6a9287c6cf7f03dcabbda0/oscm-app/javasrc/org/oscm/app/v2_0/service/APPTimerServiceBean.java#L910-L941

The error is logged internally by hibernate and triggered by method executed in line 930. In case of exception it returns null that is why it is silenced and status is not updated.
https://github.com/servicecatalog/oscm/blob/dbd251fe61def705bb6a9287c6cf7f03dcabbda0/oscm-app/javasrc/org/oscm/app/dao/OperationDAO.java#L50-L59

Potential causes:
 - race condition issue, where the entry that needs to be updated is not yet created when this method is executed or already deleted by some other thread
 - some hibernate configuration issue
 - some database trigger that interferes with the update

**Comment by elfriedegoetz** [comment]
I would like to point out that aws works correctly
