### ISSUE TITLE
VMware provisioning failed

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#182]
When trying to provision a VM with vmware connector the following exception occurs and the provisioning stops:

Caused by: java.net.UnknownHostException: UnknownHostException invoking https://xxxx.local/sdk/vimService?wsdl: none
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1385)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1369)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:653)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
        at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
        at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)

Details see log-file. Certificate and VMware user are correctly installed. The server is known and reachable.

**Comment by uhu133** [comment]
[app-vmware.log](https://github.com/servicecatalog/oscm/files/2581036/app-vmware.log)

**Comment by uhu133** [comment]
[app-vmware.log](https://github.com/servicecatalog/oscm/files/2584279/app-vmware.log)

**Comment by GoebelL** [comment]
This issue does not reproduce in our test environment. 
From [VMWareClient source code ](https://github.com/servicecatalog/oscm/blob/master/oscm-app-vmware/javasrc/org/oscm/app/vmware/remote/vmware/VMwareClient.java#L92) we can see that only the  SDK is interacting with vim service here. 
Since the the WS call is attempted, it was successful to retrieve the wsdl. However the destination host name is resolved to "none" at this point. The question is where this is coming from.

**Comment by uhu133** [comment]
A simple VMware VIM Hello World sample is running properly on this server - see files attached.
So I assume some error in the code calling the VIM.

**Comment by uhu133** [comment]
[HelloWorld.zip](https://github.com/servicecatalog/oscm/files/2591081/HelloWorld.zip)

**Comment by GoebelL** [comment]
@uhu133 
There is only one single difference I can spot between your 'hello word' application and the VMWareClient:
The client uses a custom ```javax.net.ssl.HostnameVerifier``` to grant access to all host names while your application doesn't. 
I found some posts that look at most partially related here and point to [JDK 1.8 bugs](https://bugs.java.com/view_bug.do?bug_id=JDK-8144567). 
Although it doesn't yet explain why the client is happily connecting in our environments, while in yours it doesn't. But maybe that's just a coincident, since the SSL chain is very simple at our site. 

All what I read, it's worth a try to build a patch with removing [this line](https://github.com/servicecatalog/oscm/blob/master/oscm-app-vmware/javasrc/org/oscm/app/vmware/remote/vmware/VMwareClient.java#L77).

**Comment by uhu133** [comment]
I also added javax.net.ssl.HostnameVerifier to the HelloWorld example. With you line. And it works fine.
So the code is almost the same. 

Regarding the environment: The HelloWorld Example runs within the oscm-app container.

**Comment by GoebelL** [comment]
You are using direct access without proxy. Please check the proxy is set correctly. Execute oscm-app container and check /opt/apache-tomee/conf/catalina.properties and /opt/apache-tomee/bin/catalina.sh.
Check the value that is composed for JAVA_OPTS.

**Comment by uhu133** [comment]
Uncommenting all proxy-settings in catalina_templates.sh and .properties helped

**Comment by GoebelL** [comment]
@uhu133 
Following condition in catalina.sh should fix it.

```
if eval $PROXY_ENABLED ; then
  JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=$PROXY_HTTP_HOST"

  JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyPort=$PROXY_HTTP_PORT"

  JAVA_OPTS="$JAVA_OPTS -Dhttps.proxyHost=$PROXY_HTTPS_HOST"

  JAVA_OPTS="$JAVA_OPTS -Dhttps.proxyPort=$PROXY_HTTPS_PORT"

  JAVA_OPTS="$JAVA_OPTS -Dhttp.nonProxyHosts=$PROXY_NOPROXY"
fi; 
```

**Comment by GoebelL** [comment]
This fix is available on DockerHub. Pull the images with latest tag as described [here](https://hub.docker.com/r/servicecatalog/oscm-deployer/).
