### ISSUE TITLE
Loadbalancer Exception on provisioning

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#229]
**Version Info**
tag:portgroup
 
**Describe the bug**
When leaving the host open as technical parameter an exeception is thrown:

.local
[02/25 11:34:35] [EjbTimerPool - 2] INFO  cloneVMFromTemplate() template: SUSE 11
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG Datacenter: DCFJDEMO Cluster: CLUS1FJDEMO Template: SUSE 11
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG Found system disk in VM SUSE 11  label: Hard disk 1 type: null summary: 8,388,608 KB
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG Requested disk space: 4.194304E7Template disk space: 8388608 template: SUSE 11
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG datacenter: DCFJDEMO cluster: CLUS1FJDEMO
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG vcenter: vcenter.fjdemo.local datacenter: DCFJDEMO cluster: CLUS1FJDEMO
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG target host not set. get host and storage from loadbalancer
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG datacenter: DCFJDEMO cluster: CLUS1FJDEMO
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addHostSystem host: 10.100.102.162
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.162 storage: datastore1 (2)
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.162 storage: vsanDatastore
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addHostSystem host: 10.100.102.163

[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.163 storage: datastore1
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.163 storage: vsanDatastore
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addHostSystem host: 10.100.102.164
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.164 storage: datastore1 (3)
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.164 storage: vsanDatastore
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addHostSystem host: 10.100.102.165
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.165 storage: datastore1 (1)
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG addStorage host: 10.100.102.165 storage: vsanDatastore
[02/25 11:34:35] [EjbTimerPool - 2] ERROR Failed to create VM of instance 1551094429492
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 78; cvc-elt.1: Cannot find the declaration of element 'vcenter.fjdemo.local'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1901)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at org.oscm.app.vmware.business.balancer.XMLHelper.convertToDocument(XMLHelper.java:64)
        at org.oscm.app.vmware.business.balancer.LoadBalancerConfiguration.initialize(LoadBalancerConfiguration.java:60)
        at org.oscm.app.vmware.business.balancer.LoadBalancerConfiguration.<init>(LoadBalancerConfiguration.java:46)
        at org.oscm.app.vmware.business.Template.setHostAndStorage(Template.java:431)
        at org.oscm.app.vmware.business.Template.cloneVM(Template.java:138)
        at org.oscm.app.vmware.business.statemachine.CreateActions.createVM(CreateActions.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.oscm.app.vmware.business.statemachine.States.invokeAction(States.java:74)
        at org.oscm.app.vmware.business.statemachine.StateMachine.executeAction(StateMachine.java:98)
        at org.oscm.app.vmware.service.VMController.getInstanceStatus(VMController.java:177)
        at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:100)
        at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:252)
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347)
        at com.sun.proxy.$Proxy238.getInstanceStatus(Unknown Source)
        at org.oscm.app.adapter.APPlatformControllerAdapter.getInstanceStatus(APPlatformControllerAdapter.java:67)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleControllerProvisioning(APPTimerServiceBean.java:305)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleSystems(APPTimerServiceBean.java:287)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.handleTimer(APPTimerServiceBean.java:218)
        at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.AroundTimeout(StatsInterceptor.java:145)
        at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.singleton.SingletonContainer._invoke(SingletonContainer.java:272)
        at org.apache.openejb.core.singleton.SingletonContainer.invoke(SingletonContainer.java:221)
        at org.apache.openejb.core.timer.EjbTimerServiceImpl.ejbTimeout(EjbTimerServiceImpl.java:800)
        at org.apache.openejb.core.timer.EjbTimeoutJob.execute(EjbTimeoutJob.java:39)
        at org.apache.openejb.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[02/25 11:34:35] [EjbTimerPool - 2] DEBUG Transition from current state 'CREATE_VM' with event 'failed' into state 'ERROR'

**How to Reproduce**
book a VM.
leave host open

**Additional Info **

Query from cluster table (DB)

\<?xml version="1.0" encoding="UTF-8" standalone="no"?> \<vcenter.fjdemo.local> \<balancer class="org.oscm.app.vmware.business.balancer.DynamicEquipartitionHostBalancer" cpuWeight="" memoryWeight="" vmWeight="" /> \</vcenter.fjdemo.local\>

![image](https://user-images.githubusercontent.com/32158057/53335165-04ccfb00-38fb-11e9-8e64-1532ce080a80.png)

**Comment by GoebelL** [comment]
Hi @uhu133 
for using the load balancer you need to give a valid XML. The given database contains invalid XML data for the load balancer configuration: "vcenter.fjdemo.local" is not an existing element. 

Please find [the Schema definition](https://github.com/servicecatalog/oscm/blob/master/oscm-app-vmware/javares/META-INF/Loadbalancer_schema.xsd) and [Sample XML](https://github.com/servicecatalog/oscm/blob/master/oscm-app-vmware/resources/xml/loadbalancer_config.xml) in this repo.

Note that with latest OSCM version you can import the load balancer configuraton from a CSV file. Now the data is validated at import time, in order to avoid such errors appear lately at provisioning.

**Comment by uhu133** [comment]
ok - understood
