### ISSUE TITLE
No possibility to recover password

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#32]
[Version] OSCM 17.5.0 2017/11/03
Docker image with TomEE

[How to reproduce]

1.Go to oscm-portal
 2.On login screen click "Forgot your password?"

[Expected result]
The recoverPassword page is displayed
We can fill in "User ID" and rewrite "Word verification"

[Observed result]
The recoverPassword page is displayed
We can fill in "User ID" but we cannot rewrite "Word verification", because the word is not generated. 

[Details]
![recoverpass](https://user-images.githubusercontent.com/18006407/32375254-3bd9bcba-c0a1-11e7-923d-40d428ad8b35.PNG)

**Comment by GoebelL** [comment]
@kwodzynski 
Please attach your log files.

**Comment by kwodzynski** [comment]
[catalina.2017-11-13.log](https://github.com/servicecatalog/oscm/files/1466249/catalina.2017-11-13.log)

@GoebelL I attached my oscm-core log, but there is nothing about problem with recover the password. If you want another log file, please let me know

**Comment by grubskim** [comment]
Log from the debugger during captcha creation:
```
java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
	at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
	at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:163)
	at java.awt.Font.createGlyphVector(Font.java:2526)
	at org.oscm.ui.captcha.ImageProducer.createImage(ImageProducer.java:81)
	at org.oscm.ui.captcha.Captcha.createCaptcha(Captcha.java:88)
	at org.oscm.ui.servlet.ImageServlet.createCaptcha(ImageServlet.java:60)
	at org.oscm.ui.servlet.ImageServlet.createCaptcha(ImageServlet.java:214)
	at org.oscm.ui.servlet.ImageServlet.process(ImageServlet.java:114)
	at org.oscm.ui.servlet.ImageServlet.doPost(ImageServlet.java:94)
	at org.oscm.ui.servlet.ImageServlet.doGet(ImageServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.oscm.ui.filter.DisableUrlFilter.doFilter(DisableUrlFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.oscm.ui.filter.IllegalRequestParameterFilter.doFilter(IllegalRequestParameterFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.oscm.ui.filter.HttpMethodFilter.doFilter(HttpMethodFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.oscm.ui.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by grubskim** [comment]
Possibly issue with OpenJDK, investigating further.

**Comment by grubskim** [comment]
Fixed through the oscm-dockerbuild repository in commit [da0073](https://github.com/servicecatalog/oscm-dockerbuild/commit/da007357d29f081568471c6ccac7a66cf703542f).

The reason was the Helvetica font missing from the suse image which oscm is based on. This font is used for the captcha creation.

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/11/29 - it works as expected

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/12/06 - it works as expected
