### ISSUE TITLE
Update configuration settings

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#416]
**Version Info**
OSCM 18.0 OIDC Version

**Describe the bug**
Login as a technology provider, go to "Update configuration settings" and klick save. You will redirect to the "The operation failed." screen. Even if you change a value, this screens shows up.

**How to Reproduce**
1. Go to update configuration settings
2. Click on save
3. See error

**Additional context**
It seems that there is a problem with the validation of the SSO_DEFAULT_TENANT_ID. The error occures in the ConfigurationSettingAssembler.validate(ConfigurationSetting dbConfigSetting,
            VOConfigurationSetting voConfigurationSetting)

Log:
Caused by: javax.ejb.EJBException: The bean encountered a non-application exception; nested exception is:
        java.lang.NumberFormatException: For input string: "default"
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.convertException(BaseEjbProxyHandler.java:447)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:351)
        at com.sun.proxy.$Proxy312.saveConfigurationSettings(Unknown Source)
        at org.oscm.ui.beans.operator.ConfigurationSettingsBean.save(ConfigurationSettingsBean.java:275)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
        at org.apache.webbeans.el22.WrappedMethodExpression.invoke(WrappedMethodExpression.java:52)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        at org.oscm.ui.common.ExceptionActionListener.processAction(ExceptionActionListener.java:41)
        ... 67 more
Caused by: java.lang.NumberFormatException: For input string: "default"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.valueOf(Long.java:803)
        at org.oscm.validator.BLValidator.isLongEnough(BLValidator.java:919)
        at org.oscm.configurationservice.assembler.ConfigurationSettingAssembler.validate(ConfigurationSettingAssembler.java:160)
        at org.oscm.configurationservice.assembler.ConfigurationSettingAssembler.updateConfigurationSetting(ConfigurationSettingAssembler.java:104)
        at org.oscm.operatorservice.bean.OperatorServiceBean.saveConfigurationSetting(OperatorServiceBean.java:877)
        at org.oscm.operatorservice.bean.OperatorServiceBean.saveConfigurationSettings(OperatorServiceBean.java:1218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.oscm.interceptor.ExceptionMapper.mapEJBExceptions(ExceptionMapper.java:49)
        at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.oscm.interceptor.InvocationDateContainer.setTransactionTime(InvocationDateContainer.java:41)
        at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:100)
        at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:252)
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347)
        ... 80 more

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-interfaces/pull/23

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-interfaces/pull/23
