### ISSUE TITLE
Token expiration handling

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#450]
**Version Info**
18.1 SSO

**Describe the bug**
Token expiration is not handled properly.

**How to Reproduce**
Steps :
1. Log in to oscm-portal as administrator 
3. Being logged leave the browser stale for some time (5 - 10 min?)
4. Attempt creating and organization (to initiate communication with OIDC)
5. Run `docker logs oscm-identity` 

**Observed behavior**
oscm-identity:  "javax.xml.bind.ValidationException: Id token has expired"
oscm-core: "Authentication token validation failed". 

**Expected behavior**
Connection remains active and user can continue operations as normal. Token expiration and refresh need to happen behind the scenes, intransparently for end users. 

**Additional context**
2019-09-19 10:37:00.171 ERROR 49 --- [nio-9090-exec-3] o.o.i.error.DefaultExceptionHandler      : Id token has expired

javax.xml.bind.ValidationException: Id token has expired
        at org.oscm.identity.oidc.validation.strategy.AccessTokenExpirationTimeValidationStrategy.execute(AccessTokenExpirationTimeValidationStrategy.java:34) ~[classes!/:1.0-SNAPSHOT]
        at org.oscm.identity.oidc.validation.AuthTokenValidator.doCheckAgainst(AuthTokenValidator.java:77) ~[classes!/:1.0-SNAPSHOT]
        at org.oscm.identity.oidc.validation.AuthTokenValidator.validate(AuthTokenValidator.java:60) ~[classes!/:1.0-SNAPSHOT]
        at org.oscm.identity.controller.MainController.verifyToken(MainController.java:149) ~[classes!/:1.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]

**Comment by GoebelL** [comment]
@kowalczyka @adamczykba 
Please check if this task will still be needed once the token refresh is implemented in oscm-commons and validation handling is refactored.

**Comment by kowalczyka** [comment]
Closing as this will be done within: https://github.com/servicecatalog/oscm/issues/458 and https://github.com/servicecatalog/oscm/issues/457
