### ISSUE TITLE
Operations failed after copying  a marketable service

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#469]
**Version Info**
Open Service Catalog Manager 18.0PRIVATE-BUILD-ON-20B07902D6082019/07/09

**Describe the bug**
When clicking on 
Home=>categories=> SaaS
an error page occurs

Error
The operation failed.

The oscm-core log:

30-Sep-2019 08:51:50.033 SEVERE [https-jsse-nio-8081-exec-2] com.sun.faces.application.view.FaceletViewHandlingStrategy.handleRenderException Error Rendering View[/marketplace/services.xhtml]
 java.lang.IllegalStateException: Component ID sortUpACTIVATION_DESCENDING has already been found in the view.
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1026)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
        at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:460)
        at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:89)
        at com.sun.faces.application.view.WriteBehindStateWriter.getState(WriteBehindStateWriter.java:327)
        at com.sun.faces.application.view.WriteBehindStateWriter.flushToWriter(WriteBehindStateWriter.java:221)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:475)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at org.apache.myfaces.tomahawk.application.ResourceViewHandlerWrapper.renderView(ResourceViewHandlerWrapper.java:169)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)

**How to Reproduce**
Copied a marketable service and activated this

**Comment by GoebelL** [comment]
Hi @uhu133 
I am struggling to reproduce this. Can you share more information? What I can read from given trace log points to the next button on the pager control in the service list where the list is selected to show "Most recent first". I might be mistaken, but on the first view this scenario looks rather unrelated to categories and copied services.

**Comment by GoebelL** [comment]
Please login to the oscm-core container, pick the /logs/System.log file and  attach it.

**Comment by uhu133** [comment]
stored on temp folder

**Comment by uhu133** [comment]
not reproduceable after restart of client
