### ISSUE TITLE
Technical provider from Sample Data has no privileges to carry on the Actions in controller

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#53]
[Version] OSCM 17.5.0 2017/11/24

[How to reproduce]

1. Create new subscription for Openstack
2. Login to Openstack controller /oscm-app/controller/?controllerid=ess.openstack as techprovider (Sample data)
3. Chose some action from the "Action" list
4. Click "Execute" button

[Expected result]
The action is carried on

[Observed result]
Red message:

> The subscription cannot be terminated.: Unauthorized Access by Principal Denied while invoking public org.oscm.vo.VOSubscriptionDetails org.oscm.webservices.SubscriptionServiceWS.getSubscriptionForCustomer(java.lang.String,java.lang.String) throws org.oscm.types.exceptions.ObjectNotFoundException,org.oscm.types.exceptions.OperationNotPermittedException with params [a4050753, Openstack]. 

and error in log: 

> 
24-Nov-2017 08:24:29.996 WARNING [http-nio-8080-exec-7] org.apache.cxf.phase.PhaseInterceptorChain.doDefaultLogging Application {http://oscm.org/xsd}SubscriptionService#{http://oscm.org/xsd}getSubscriptionForCustomer has thrown exception, unwinding now
 org.apache.cxf.interceptor.Fault: Unauthorized Access by Principal Denied while invoking public org.oscm.vo.VOSubscriptionDetails org.oscm.webservices.SubscriptionServiceWS.getSubscriptionForCustomer(java.lang.String,java.lang.String) throws org.oscm.types.exceptions.ObjectNotFoundException,org.oscm.types.exceptions.OperationNotPermittedException with params [a4050753, Openstack].
        at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:166)
        at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.createFault(AbstractJAXWSMethodInvoker.java:267)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:140)
        at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:232)
        at org.apache.openejb.server.cxf.ejb.EjbMethodInvoker.invoke(EjbMethodInvoker.java:84)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:74)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.openejb.server.cxf.ejb.EjbInterceptor.intercept(EjbInterceptor.java:140)
        at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:97)
        at org.apache.openejb.core.stateless.StatelessContainer.invokeWebService(StatelessContainer.java:323)
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:247)
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212)
        at org.apache.openejb.server.cxf.ejb.EjbMethodInvoker.preEjbInvoke(EjbMethodInvoker.java:125)
        at org.apache.openejb.server.cxf.ejb.EjbMethodInvoker.invoke(EjbMethodInvoker.java:82)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:74)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$2.run(ServiceInvokerInterceptor.java:126)
        at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:131)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:262)
        at org.apache.openejb.server.cxf.CxfWsContainer.onMessage(CxfWsContainer.java:85)
        at org.apache.openejb.server.webservices.WsServlet.service(WsServlet.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ejb.EJBAccessException: Unauthorized Access by Principal Denied
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:189)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347)
        at com.sun.proxy.$Proxy286.getSubscriptionForCustomer(Unknown Source)
        at org.oscm.webservices.SubscriptionServiceWS.getSubscriptionForCustomer(SubscriptionServiceWS.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:100)
        at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.server.cxf.ejb.EjbMethodInvoker.performInvocation(EjbMethodInvoker.java:92)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        ... 49 more

**Comment by grubskim** [comment]
There are following problems with this:
1) RolesAllowed: "SERVICE_MANAGER", "BROKER_MANAGER", "RESELLER_MANAGER".
Technical provider does not have SERVICE_MANAGER role so I assigned it to him, but then:
2) TP is not a supplier of the customer which created the subscription, so i created this assignment, then:
3) TP is not a supplier.

So the solutions would be:
A) In sample data, prepare user who is the technology provider and the supplier at the same time, or
B) Change logic for permission check (should these operations be allowed not only for supplier but also for technology manager?

@GoebelL 
Please advise which one is better.

**Comment by GoebelL** [comment]
Let's keep it simple. I would go for A.  
However, steps 2. and 3. are not exactly clear for me. This appears as if your assignment operation after 2. didn't change anything. So, did you grant the Supplier role to the TP organization?

**Comment by GoebelL** [comment]
Please check this again.

**Comment by grubskim** [comment]
No, I didn't. I just created an entry by hand in the organizationreference table, so technically TP didn't have the supplier role.

**Comment by grubskim** [comment]
Issue resolved by @kowalczyka with changes in sample data.
