### ISSUE TITLE
Improve login of OSCM Swagger UI and description

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#659]
**Version Info**
v18.1 internal mode 

**Describe the bug**
Failed to login to Swagger UI at https://FQDN:8081/oscm-rest-api. It keeps looping the authentication dialog.

**How to Reproduce**
1. Type 'docker logs -f oscm-core' on command-line to trace the log messages
2. Open https://FQDN:8081/oscm-rest-api in you client browser
3. On authentication prompt enter the credentials for the platform administrator
3. See error trace

**Observed behavior**
The authentication prompt returns without login. Error messages are shown.

**Expected behavior**
Login successful.

**Screenshots**
N/A

**Additional context**
```
17-Feb-2020 15:08:00.974 WARNING [https-jsse-nio-8081-exec-2] sun.reflect.NativeMethodAccessorImpl.invoke Login exception authenticating username "administrator"
 javax.security.auth.login.LoginException: Authentication failed
        at org.oscm.security.ADMLoginModule.login(ADMLoginModule.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.catalina.realm.JAASRealm.authenticate(JAASRealm.java:425)
        at org.apache.catalina.realm.JAASRealm.authenticate(JAASRealm.java:342)
        at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:195)
        at org.apache.tomee.catalina.TomEERealm.authenticate(TomEERealm.java:48)
        at org.apache.catalina.authenticator.BasicAuthenticator.doAuthenticate(BasicAuthenticator.java:73)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:556)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by GoebelL** [comment]
Hi @cworf91
I just discovered that the application actually requires the _user key_ for login. Thus login with '1000' and administrator password should succeed. However neither this works :-( I debugged the part and found that login does succeed, but eventually the request results in HTTP 404. This might be fixed already. I tested with an older intermediate version. Probably I have picked a bad one.
Therefore, please check again with OSCM latest.

**Comment by cworf91** [comment]
Hi @GoebelL 
as we discovered, in the latest version it works.
What should be noticed here is that oscm-ip have to be replaced.

**Comment by cworf91** [comment]
The Problem is now described here
https://github.com/servicecatalog/oscm-rest-api/issues/182

**Comment by GoebelL** [comment]
The readme description on oscm-rest-api repo needs some polishing on wording and content. First of all, the UI prompt as well as the readme should clearly mention that the user needs to login with his user key (!). Nobody will intuit that the user id doesn't work here.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-rest-api/pull/186
